name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Print Hello World
      run: |
        echo "Hello World"
        echo ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}
    - name: Print SECRET Without Mast
      run: echo ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }} | sed 's/./& /g'
    - name: Build with Gradle
      run: ./gradlew build
